name: 💡 Feature Request
description: For any ideas or feature requests
labels: ['💡 feature request']

body:
  - type: markdown
    attributes:
      value: |
        Please describe your idea in as much detail as possible so that we can efficiently process your request.

  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
