name: ❓ Ask a Question
description: Any questions about this repository
labels: ['❓ question']

body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
